# Site
title:              Etiker
bio:                'The blog for Etiker, an ethics advisor for tech companies'
description:        "Discussions on tech, ethics, and society, led by the team at Etiker"
locale:             en_US
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.etiker.com" # the base hostname & protocol for your site

defaults:
- scope:
    path: ''
    type: posts
  values:
    permalink: "/blog/:title/"
    layout: post
    author: Etiker Team

# Jekyll
permalink:          /blog/:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:   default

# Social
twitter:            EtikerCo
facebook:           EtikerCo
github:             EtikerCo

# personal
location:           Ottawa, ON
phone:              613-701-7709
email:              hello@etiker.com

# Gems
plugins:
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

paginate: 6
paginate_path: "/blog/page:num/"

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile, old]
